backend: tensorflow
class_name: Model
config:
  input_layers:
  - - input_1
    - 0
    - 0
  - - input_2
    - 0
    - 0
  layers:
  - class_name: InputLayer
    config:
      batch_input_shape: !!python/tuple
      - 110
      - 1
      dtype: float32
      name: input_1
      sparse: false
    inbound_nodes: []
    name: input_1
  - class_name: InputLayer
    config:
      batch_input_shape: !!python/tuple
      - 351
      - 1
      dtype: float32
      name: input_2
      sparse: false
    inbound_nodes: []
    name: input_2
  - class_name: Dense
    config:
      activation: tanh
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: normal
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_1
      trainable: true
      units: 16
      use_bias: true
    inbound_nodes:
    - - - input_1
        - 0
        - 0
        - {}
    - - - input_2
        - 0
        - 0
        - {}
    name: dense_1
  - class_name: Dense
    config:
      activation: tanh
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: normal
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_5
      trainable: true
      units: 16
      use_bias: true
    inbound_nodes:
    - - - input_1
        - 0
        - 0
        - {}
    - - - input_2
        - 0
        - 0
        - {}
    name: dense_5
  - class_name: Dense
    config:
      activation: tanh
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: normal
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_2
      trainable: true
      units: 8
      use_bias: true
    inbound_nodes:
    - - - dense_1
        - 0
        - 0
        - {}
    - - - dense_1
        - 1
        - 0
        - {}
    name: dense_2
  - class_name: Dense
    config:
      activation: tanh
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: normal
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_6
      trainable: true
      units: 8
      use_bias: true
    inbound_nodes:
    - - - dense_5
        - 0
        - 0
        - {}
    - - - dense_5
        - 1
        - 0
        - {}
    name: dense_6
  - class_name: Dense
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: normal
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_9
      trainable: true
      units: 1
      use_bias: true
    inbound_nodes:
    - - - dense_2
        - 0
        - 0
        - {}
    - - - dense_2
        - 1
        - 0
        - {}
    name: dense_9
  - class_name: Dense
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config:
          distribution: normal
          mode: fan_avg
          scale: 1.0
          seed: null
      kernel_regularizer: null
      name: dense_10
      trainable: true
      units: 1
      use_bias: true
    inbound_nodes:
    - - - dense_6
        - 0
        - 0
        - {}
    - - - dense_6
        - 1
        - 0
        - {}
    name: dense_10
  - class_name: Ansatz
    config:
      name: ansatz_1
      trainable: true
    inbound_nodes:
    - - - dense_9
        - 0
        - 0
        - &id001 {}
      - - dense_10
        - 0
        - 0
        - *id001
    name: ansatz_1
  - class_name: Ansatz
    config:
      name: ansatz_2
      trainable: true
    inbound_nodes:
    - - - dense_9
        - 1
        - 0
        - &id002 {}
      - - dense_10
        - 1
        - 0
        - *id002
    name: ansatz_2
  - class_name: Mask
    config:
      name: SLACP
      trainable: true
    inbound_nodes:
    - - - ansatz_1
        - 0
        - 0
        - {}
    name: SLACP
  - class_name: Mask
    config:
      name: BCDMSP
      trainable: true
    inbound_nodes:
    - - - ansatz_2
        - 0
        - 0
        - {}
    name: BCDMSP
  name: model_4
  output_layers:
  - - SLACP
    - 0
    - 0
  - - BCDMSP
    - 0
    - 0
keras_version: 2.2.4
